name: My Workflow
on: [push]

jobs:
  my_job:
    name: My Job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: run my shit
        run: |
          ./static-nix --store $HOME/.cache/nix/store -f channel:nixpkgs-unstable \
              run nixpkgs.hello -c hello
